### PR TITLE
Use native language for chokidar

### PR DESCRIPTION
**Pull request by es128**
Considering the origins of chokidar's name, this really seems like a more appropriate way to proceed with the codebase prior to releasing 1.0.0.

### CODE REVIEW

**Comment by paulmillr** [comment]
I love this idea!

**Comment by sullinger** [comment]
Seriously?! Is this your April Fools Day contribution?

I can not read the source code anymore and I think many others can't either.
So you limit the number of contributors and users of this library, as no one wants to use a library he/she can not evaluate regarding code quality, or step through and understand what's happening while debugging.

Why not just minify the sources now? If you can not read/understand the variable names, then you can replace them with shorter words or single letters. This merged PR is bullshit and in combination with the amount of issues that came up in the last weeks it forces me to search for alternatives.

**Comment by es128** [comment]
Lolololol

**Comment by sullinger** [comment]
Wrong language. I can still read your lol! xD

**Comment by floatdrop** [comment]
@es128 this broken everything on windows. Why would you do that?

**Comment by es128** [comment]
1. rc6 is a tagged release - npm should not provide it unless deliberately requested. You can see that if you `npm install chokidar` you get rc5. I also checked semver ranges like `^1.0.0-rc5` with `npm update` and it did not download rc6. 

2. The code should continue to work anyway. You can see that the tests passed. 

So it wasn't quite as reckless as it may have appeared. Just trying to have a little fun obviously. Sorry that it upset that user who experienced issues.

**Comment by floatdrop** [comment]
@es128 I guess npm do download updates from rc releases (gulp-watch [has `^1.0.0-rc2`](https://github.com/floatdrop/gulp-watch/blob/33d44df1a079c117a8faee3e6d49a6aa885dfb01/package.json#L43) in package). Jokes on me not to pin rc release :dog:

**Comment by es128** [comment]
Alright well it wasn't my intention to cause disruption for anyone. Thanks for taking it in stride.

**Comment by paulmillr** [comment]
Just pulled it from NPM. Sorry again.

**Pull request merged**
