### PR TITLE
Fix process not exiting calling .close() right after watching.

### LINKED ISSUE #434: Node doesn't exit after closing watch
After setting up, then closing, a watcher, the Node process doesn't exit.
Windows.

``` javascript
const chokidar = require('chokidar')
const options = {}
const directoryPath = srcPath
// configuration taken from webpack
const watcher = chokidar.watch(directoryPath, {
    ignoreInitial: true,
    persistent: true,
    followSymlinks: false,
    depth: 0,
    atomic: false,
    alwaysStat: true,
    ignorePermissionErrors: true,
    usePolling: options.poll ? true : undefined,
    interval: typeof options.poll === "number" ? options.poll : undefined
});
watcher.close()
```

### PR DESCRIPTION
**Pull request by satazor**
Attempts to fix #434 

@es128 can you review this when you got some time?

Cheers

### CODE REVIEW

**Comment by satazor** [comment]
Strange.. tests pass on my macOS machine but are all failing on travis.

**Comment by es128** [comment]
The Travis OS X failures may be unrelated, it's always a struggle with those. 

But please do try to figure out the issue on Linux. The nodefs side of this patch may not be working the way you've intended.

**Comment by satazor** [comment]
Actually the test I've added is passing on all macOSx @ travis but are failing on linux. Will spawn my linux vm and investigate.

**Comment by satazor** [comment]
@es128 Should be good now. Some unrelated tests sometimes fail, sometimes they pass.

**Comment by satazor** [comment]
@es128 Did you find the time to check this PR?

**Comment by es128** [comment]
Just wanted to see the new test pass in appveyor.

Looks good, thanks!

**Comment by satazor** [comment]
@edi9999 Cool! Shall we expect a new release soon?

**Comment by edi9999** [comment]
You probably meant @es2016

**Comment by satazor** [comment]
Oh yea sorry :p

**Comment by satazor** [comment]
@es128 Bump :D

**Pull request merged**
