### PR TITLE
Use realPath instead of path on watchers

### PR DESCRIPTION
**Pull request by RoXuS**
Attempt to fix https://github.com/paulmillr/chokidar/issues/1040

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
@paulmillr is this a good solution for this issue?

**Comment by paulmillr** [comment]
The problem with chokidar is that since it's used so much, even a change like this needs to be tested manually in apps etc. So just need to test it...

**Comment by RoXuS** [comment]
hey! Any news on this PR? All of my mate have this issues on mac...

Can I help on something?

**Comment by paulmillr** [comment]
would be great if you had a test for the case

**Comment by RoXuS** [comment]
@paulmillr, I added the test, it was hard to reproduce from scratch.
I have to create more than 10 folders to reach the `consolidateThreshold` then I add symlink on each and I listen these symlinks with chokidar.
When the `consolidateThreshold` is reached, the watch folders are set to the parent then the `change` events aren't listen anymore.

If you comment my change on `fsevents-handler.js` you will see that the event is never fired and the test failed.


If can I do something, tell me!

**Comment by RoXuS** [comment]
thx @paulmillr, me and my team will be happy ^^

**Pull request merged**
