### PR TITLE
fix: watch does not work for glob pattern '<dir>/**' if '<dir>' does not exist on fs

### PR DESCRIPTION
**Pull request by eGavr**
Resolves https://github.com/paulmillr/chokidar/issues/745

### CODE REVIEW

**Comment by srguiwiz** [comment]
@eGavr , thank you for taking initiative and fixing.

Testing is necessary.  Testing this project for now is a little bit odd, because the test suite has cases in it that don't pass, for yet to be fixed defects.

In order to ensure not to break existing functionality with a next release, please:

- Run test suite with your fix not in (previous commit), note what fails.
- Run test suite with your fix.  Compare what fails then.

That protects quality and sanity.

To be more perfect, you could also add a test case in test.js that fails before your fix and then passes with your fix.

**Comment by eGavr** [comment]
@srguiwiz 

I've created a testing pull request https://github.com/paulmillr/chokidar/pull/749 where I've just changed  README and you can see in it that there are 7 broken tests.

In my PR there were 7 broken tests too. 
Then I've wrote a test on my changed, push it and I see that there are 6 broken tests for now :)

I think that some the test are not stable and fail randomly.

Can you review my chnages, please? It seems that they do not break the current functionality and fix the problem which I've described in the issue.

**Comment by eGavr** [comment]
For now there are 9 broken tests :(

The previous commit which is different from the latest one only in test name has 7 broken tests.

**Comment by eGavr** [comment]
ping :)

**Pull request closed without merging**
