### PR TITLE
Update CI config

### PR DESCRIPTION
**Pull request by XhmikosR**
* specify `FORCE_COLOR: 2` for colored output
* update `actions/checkout` to v2
* update `actions/setup-node` to v2

@paulmillr I see CI is still flaky :/

### CODE REVIEW

**Comment by paulmillr** [comment]
@XhmikosR what's the difference from v1?

**Comment by XhmikosR** [comment]
They don't have a clear changelog but there have been many fixes and new features:

* https://github.com/actions/checkout#whats-new
* https://github.com/actions/setup-node/releases

**Comment by XhmikosR** [comment]
Should I add Node.js 16 while at it?

**Comment by XhmikosR** [comment]
Ah, I just saw you have a v4 branch too. Happy to make these tweaks there too later.

**Comment by paulmillr** [comment]
Use this:

```
        with:
          node-version: ${{ matrix.node }}
```

**Comment by XhmikosR** [comment]
Not sure what you mean?

**Pull request merged**
