### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by paulmillr**

### CODE REVIEW

**Comment by paulmillr** [comment]
@XhmikosR what about `race2 condition`? Should we bring it back?

**Comment by XhmikosR** [comment]
I thought it was identical to the other race condition test? Let me have a closer look first.

**Comment by XhmikosR** [comment]
I think it's identical in essence.

**Comment by XhmikosR** [comment]
Actually, now I'm able to reproduce the Windows test failure on my laptop, both master and this branch:

```
  1) chokidar
       fs.watch (non-polling)
         watch glob patterns
           should traverse subdirs to match globstar patterns:
     expected spy to have been called exactly once, but it was called twice
    spy(change, C:\Users\xmr\Desktop\chokidar\test-fixtures\26\subdir\subsub\ab.txt, [Stats] {
  atime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
  atimeMs: 1572338120324.312,
  birthtime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
  birthtimeMs: 1572338120262.179,
  blksize: 4096,
  blocks: 0,
  ctime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
  ctimeMs: 1572338120324.312,
  dev: 2416354017,
  gid: 0,
  ino: 9851624185451478,
  mode: 33206,
  mtime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
  mtimeMs: 1572338120324.312,
  nlink: 1,
  rdev: 0,
  size: 13,
  uid: 0
}) at FSWatcher.emit (events.js:210:5)

    spy(change, C:\Users\xmr\Desktop\chokidar\test-fixtures\26\add.txt, [Stats] {
  atime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
  atimeMs: 1572338120324.312,
  birthtime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
  birthtimeMs: 1572338120324.312,
  blksize: 4096,
  blocks: 0,
  ctime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
  ctimeMs: 1572338120324.312,
  dev: 2416354017,
  gid: 0,
  ino: 3659174697817051,
  mode: 33206,
  mtime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
  mtimeMs: 1572338120324.312,
  nlink: 1,
  rdev: 0,
  size: 13,
  uid: 0
})
  AssertionError: expected spy to have been called exactly once, but it was called twice
      spy(change, C:\Users\xmr\Desktop\chokidar\test-fixtures\26\subdir\subsub\ab.txt, [Stats] {
    atime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
    atimeMs: 1572338120324.312,
    birthtime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
    birthtimeMs: 1572338120262.179,
    blksize: 4096,
    blocks: 0,
    ctime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
    ctimeMs: 1572338120324.312,
    dev: 2416354017,
    gid: 0,
    ino: 9851624185451478,
    mode: 33206,
    mtime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
    mtimeMs: 1572338120324.312,
    nlink: 1,
    rdev: 0,
    size: 13,
    uid: 0

      spy(change, C:\Users\xmr\Desktop\chokidar\test-fixtures\26\add.txt, [Stats] {
    atime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
    atimeMs: 1572338120324.312,
    birthtime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
    birthtimeMs: 1572338120324.312,
    blksize: 4096,
    blocks: 0,
    ctime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
    ctimeMs: 1572338120324.312,
    dev: 2416354017,
    gid: 0,
    ino: 3659174697817051,
    mode: 33206,
    mtime: Tue Oct 29 2019 10:35:20 GMT+0200 (GMT+02:00),
    mtimeMs: 1572338120324.312,
    nlink: 1,
    rdev: 0,
    size: 13,
    uid: 0
  })
      at Context.<anonymous> (test.js:812:46)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by XhmikosR** [comment]
The macOS failure on CI points to an unhandled promise rejection: https://github.com/paulmillr/chokidar/pull/941/checks?check_run_id=279010465#step:5:346

**Comment by XhmikosR** [comment]
OK, I give up. Tests are too complex to figure this out... If they were split, it might have been easier.

**Comment by paulmillr** [comment]
Do you know you can run just one test via `it.only`?

**Comment by XhmikosR** [comment]
Yup. But this issue is so weird. After a while that I tried again, it
passed fine locally. So this makes it really hard to pinpoint the root
cause.

Only CI seems to fail consistently, but not always in the same test. Maybe
in the same suite, though.

I'll try again tomorrow only on one OS per time.

**Comment by XhmikosR** [comment]
@paulmillr here's what I've seen so far. Feel free to push to this PR's branch, do not merge until we are ready please.

1. After switching to `rimraf.sync` on my machine I get

    ```
     2) chokidar
           "after all" hook for "should expose public API methods":
         Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\xmr\Desktop\chokidar\test-fixtures'
          at Object.rmdirSync (fs.js:752:3)
          at rmkidsSync (node_modules\rimraf\rimraf.js:357:27)
          at rmdirSync (node_modules\rimraf\rimraf.js:337:7)
          at Function.rimrafSync [as sync] (node_modules\rimraf\rimraf.js:307:9)
          at Context.<anonymous> (test.js:2030:12)
          at processImmediate (internal/timers.js:439:21)
    ```
    
    Which means something leaves something open, I think
2. It seems `should correctly handle glob with braces` test fails both on Windows and macOS, consistently AFAICT. Ubuntu seems to pass in the last runs, but please restart the workflow to confirm

I still believe we should modularize the test files. Move them in the test folder, move utilities outside of the main tests and have each suite as a separate file. It should help pinpoint issues more easily. But being I'm not as familiar with the codebase  as you, it's something that only you could try doing in another branch, assuming you agree.

**Comment by paulmillr** [comment]
Re: splitting the tests — Great idea, we’ve had an issue for that for a long time. Unfortunately, not super simple. The reason: we run tests up to three times with a custom runTests function. If we can refactor this, it would be great.

**Comment by XhmikosR** [comment]
If I revert the `rimraf.sync` patch, then tests pass for me again locally on Windows.

Maybe I should just drop this patch and we merge the rest?

Splitting the tests is indeed quite big. We first need to identify the common functions, but that's not so hard. My problem is all those vars that are being reset/changed through tests.

Maybe we should start doing it in another branch and see how it goes.

**Comment by paulmillr** [comment]
Sure thing.

**Comment by paulmillr** [comment]
See #413 for discussion on test improvement.

**Comment by XhmikosR** [comment]
Alright, locally on Windows + Node.js 12 I get the same failure as the current CI failure https://github.com/paulmillr/chokidar/pull/941/checks?check_run_id=282969328#step:5:270

**Comment by paulmillr** [comment]
Merging for now.

**Pull request merged**
