### PR TITLE
just to see that tests fail in master without any changes

### PR DESCRIPTION
**Pull request by eGavr**

### CODE REVIEW

**Comment by srguiwiz** [comment]
This PR **not** to be merged.

Just reminder you can run on your own machine
```
npm run test
```
and get familiar with what tests pass and fail.

Of course you would first need to have installed packages with
```
npm install
```

You may have known these steps, and have intended to demonstrate output of a test run.

The output of a test run, however, already is available in the previous commit before yours, behind the red X at https://github.com/paulmillr/chokidar/commits/master under Travis CI ☺

**Comment by eGavr** [comment]
On my local machine I receive different results from time to time :)

All in all in travis this results are sometime different too

**Comment by paulmillr** [comment]
Almost fixed in master.

**Comment by paulmillr** [comment]
https://travis-ci.org/paulmillr/chokidar/builds/425232519?utm_source=github_status&utm_medium=notification

**Pull request closed without merging**
