### PR TITLE
fix: watch does not work for glob pattern which intersects with non-glob part of another glob pattern

### LINKED ISSUE #747: Watch does not work for glob pattern which  intersects with non-glob part of another glob pattern
**Describe the bug**

Files are not being watched for glob `<dir>/**` if `<dir>` does not exist.

**Versions (please complete the following information):**
 - Chokidar version [2.0.4]
 - Node version [8.6.0]
 - OS version: [Ubuntu 16.04]

**To Reproduce**

```js
// index.js
const chokidar = require('chokidar');
const watcher = chokidar.watch([
    'some-*/*/*.js',
    'some-dir/*/*.css'
]);

watcher.on('add', path => console.log(path));
```

Create files `some-dir/dir/file.css`, `some-dir/dir/file.js` and run the script.

You will see nothing in console:

```
some-dir/dir/file.css
```

No any information about `some-dir/dir/file.js`.

If then you add, for example, `some-dir/dir/another-file.js` nothing logs to console too.

### PR DESCRIPTION
**Pull request by eGavr**
Resolves #747

### CODE REVIEW

**Comment by srguiwiz** [comment]
@eGavr , thank you for taking initiative and fixing.

Testing is necessary.  Testing this project for now is a little bit odd, because the test suite has cases in it that don't pass, for yet to be fixed defects.

In order to ensure not to break existing functionality with a next release, please:

- Run test suite with your fix not in (previous commit), note what fails.
- Run test suite with your fix.  Compare what fails then.

That protects quality and sanity.

To be more perfect, you could also add a test case in test.js that fails before your fix and then passes with your fix.

**Comment by eGavr** [comment]
@srguiwiz 

I've created a testing pull request https://github.com/paulmillr/chokidar/pull/749 where I've just changed  README and you can see in it that there are 7 broken tests.

In my PR there were 7 broken tests too. 
Then I've wrote a test on my changed, push it and I see that there are 6 broken tests for now :)

I think that some the test are not stable and fail randomly.

Can you review my chnages, please? It seems that they do not break the current functionality and fix the problem which I've described in the issue.

**Comment by eGavr** [comment]
ping :)

**Comment by eGavr** [comment]
I've found some problem
Trying to fix it

**Pull request closed without merging**
