### PR TITLE
Update fsevents to the most recent minor version to remove minimist vulnerability

### PR DESCRIPTION
**Pull request by mjziolko**
https://npmjs.com/advisories/1179

### CODE REVIEW

**Comment by mjziolko** [comment]
Might need to create a new target branch to get a new minor version out with this package update.  Webpack relies on this semver and currently has a prototype pollution vulnerability in minimist: https://npmjs.com/advisories/1179

**Comment by paulmillr** [comment]
^1.2.2 includes 1.2.11. What's the deal here?

**Comment by paulmillr** [comment]
You also have invalid commit. Current chokidar 2.x branch uses fsevents `^1.2.7`.

**Comment by mjziolko** [comment]
Yup, sorry made this PR in error.  There's some issues with the semver being pinned/the mkdirp package changing hands and I've been staring at version numbers for an hour.  I'll close this!

**Pull request closed without merging**
