### PR TITLE
Ignore helix temp files

### PR DESCRIPTION
**Pull request by aster-void**
- [x] checked all tests pass

related issue (in Helix repo): https://github.com/helix-editor/helix/issues/11998

### CODE REVIEW

**Comment by paulmillr** [comment]
you can use anything you'd like in `ignored`. There is no need to edit built-ins.

**Comment by aster-void** [comment]
I see other editor's temp files ignored here, why shouldn't helix (a file editor fyi) be one of them? I think this is the most appropriate place to patch this.

**Comment by paulmillr** [comment]
Brief google says it's not exclusive to helix https://file.org/extension/bck

Again, you can adjust this in your app. It doesn't matter what's the default configuration is.

**Comment by aster-void** [comment]
neither as swp. https://file.org/extension/swp

Anyways, I'll open a patch request for vite. thanks anyways.

**Comment by 43081j** [comment]
It is only used for the atomic writes feature FYI. Since if you enable that, you want to tell chokidar to detect temp editor files that happen mid write (like swap files) 

That's why we wouldn't usually change it

**Pull request closed without merging**
