### PR TITLE
Fix filter pattern not being applied to files inside symlink subdirectories of the watched path

### PR DESCRIPTION
**Pull request by samuelneff**
This PR resolves issue #967 and applies the pattern filter to files nested inside symlinks. 

No change in expected behavior or usage. New passing test added.

### CODE REVIEW

**Comment by samuelneff** [comment]
I'll address those issues, assuming they're real issues (lint at least probably is). 👍

**Comment by samuelneff** [comment]
@paulmillr It looks like none of the errors are actually related to my PR but are existing issues. This particular one is with DTS Lint and a missing function.

**Comment by paulmillr** [comment]
As i’ve mentioned, we can’t really merge new code unless we fix the old tests.

Otherwise some stuff could get broken and we wouldn’t even know.

Thanks for the pr.

**Comment by samuelneff** [comment]
Thanks for the update. I missed that specific message about the tests. I'll work on those next. 👍

**Pull request closed without merging**
