### PR TITLE
bump is-glob

### PR DESCRIPTION
**Pull request by MhMadHamster**
bump is-glob version should fix some issues with parentheses, (!) [] etc in path, some tests for such cases need to be added probably

### CODE REVIEW

**Comment by MhMadHamster** [comment]
i think i did smth wrong while creating pr since the commits from the last one displaying as well :confused:

**Comment by es128** [comment]
@MhMadHamster yeah it's because I used the "Squash and merge" button for your last PR, so if you kept your same branch going it's going to have a diverged commit history.

But if I do the same thing with this one it probably won't end up mattering.

**Comment by MhMadHamster** [comment]
i'm not certainly sure in the correctness of current "fix", this needs more investigation

**Comment by sayp** [comment]
Макс, красава, весь хотелс за тебя кулочки держит!

**Pull request closed without merging**
