### PR TITLE
chore: remove leftover console.logs

### PR DESCRIPTION
**Pull request by 43081j**
leftover from some debugging in the v4 branch

### CODE REVIEW

**Comment by paulmillr** [comment]
FYI the v4 branch is WIP locally here and ongoing a huge refactoring. It's much more complicated then initially thought, but getting there.

**Comment by 43081j** [comment]
is there somewhere easy to reach you so we could catch up on this stuff?

would be happy to help, and it'd be nice to know what you're changing etc. i don't want to end up duplicating work but want to help get it over the line still

**Comment by paulmillr** [comment]
https://github.com/paulmillr/chokidar/tree/alpha 

Check out this document: https://gist.github.com/paulmillr/43e375be993b9a86bc43888e837345b3

**Comment by 43081j** [comment]
that's a great write up 🙏 

if you need any help along the way, just let me know

super happy you found the time to get back onto this

**Comment by paulmillr** [comment]
@43081j check out the code for `v4.ts` - any help in refactoring this is needed.

**Comment by 43081j** [comment]
if you can make a draft PR, I can leave comments too. I think that'd be helpful so I could point out any areas I'm looking at, assuming I do some

**Comment by paulmillr** [comment]
https://github.com/paulmillr/chokidar/pull/1342

**Pull request closed without merging**
